
remote_theme: pmarsceill/just-the-docs
theme: jekyll-theme-slate


# Footer "Edit this page on GitHub" link text
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/allitude/..." # the github URL for your repo
gh_edit_branch: "main"
# gh_edit_source: docs # the source that your files originate from

# "tree" or "edit" if you want the user to jump into the editor immediately
gh_edit_view_mode: "tree"
